init home work branch
MaksLeseu/React-HomeWork pull request #1
Opened 2023-02-24 20:04 UTC by MaksLeseu

2023-02-24 20:13 UTC, Alekseyfgl commented on src/s1-main/App.tsx
> +
You need to do it.

2023-02-24 20:13 UTC, Alekseyfgl commented on src/s1-main/App.tsx
> +
fdsfsd

2023-02-24 20:13 UTC, Alekseyfgl commented on src/s1-main/App.tsx
> +
dgdfgdf

2023-02-24 20:14 UTC, MaksLeseu commented on src/s1-main/App.tsx
> +
Okaj

2023-02-24 20:15 UTC, Alekseyfgl reviewed
I checked all

2023-02-24 20:15 UTC, Alekseyfgl commented on src/s1-main/App.tsx
>              {/*раскомментировать по ходу выполнения*/}
good!!!

2023-02-24 20:16 UTC, MaksLeseu commented on src/s1-main/App.tsx
> +
Okaj

2023-02-28 05:41 UTC, Alekseyfgl requested changes

2023-02-28 05:41 UTC, Alekseyfgl commented on src/s2-homeworks/hw02/HW2.tsx
> +export const filterAffairs = (affairs: Array<AffairType>, filter: string): any => { // need to fix any
fix any from return

2023-02-28 05:41 UTC, Alekseyfgl commented on src/s2-homeworks/hw02/HW2.tsx
> +export const deleteAffair = (affairs: Array<AffairType>, _id: number): any => { // need to fix any
fix any from return

2023-02-28 05:41 UTC, Alekseyfgl commented on src/s2-homeworks/hw02/HW2.tsx
>      const [affairs, setAffairs] = useState<any>(defaultAffairs) // need to fix any
fix any from useState

2023-02-28 05:41 UTC, Alekseyfgl commented on src/s2-homeworks/hw02/affairs/Affairs.tsx
> +    const setAll = (item: any) => {
What does item mean in params? I don't understand. 
and fix any

2023-02-28 05:41 UTC, Alekseyfgl commented on src/s2-homeworks/hw02/affairs/Affairs.tsx
> +        props.setFilter(item);
all the same

2023-02-28 05:41 UTC, Alekseyfgl commented on src/s2-homeworks/hw02/affairs/affair/Affair.tsx
> +        return props.deleteAffairCallback(id);
remove return

2023-02-28 05:41 UTC, Alekseyfgl commented on src/s2-homeworks/hw02/affairs/affair/Affair.tsx
>                  // need to fix
add symbol into button

2023-03-02 16:48 UTC, MaksLeseu commented on src/s2-homeworks/hw02/affairs/Affairs.tsx
> +    const setAll = (item: any) => {
I just fix any?

2023-03-02 16:53 UTC, MaksLeseu commented on src/s2-homeworks/hw02/affairs/affair/Affair.tsx
>                  // need to fix
What symbol?

2023-03-02 17:49 UTC, Alekseyfgl approved these changes

2023-03-02 17:49 UTC, Alekseyfgl commented on src/s2-homeworks/hw02/affairs/Affairs.tsx
> +    const setAll = (item: string) => {
add void for returns

2023-03-02 17:49 UTC, Alekseyfgl commented on src/s2-homeworks/hw02/affairs/Affairs.tsx
> +    const setHigh = (item: string) => {
add void for returns

2023-03-02 17:49 UTC, Alekseyfgl commented on src/s2-homeworks/hw02/affairs/affair/Affair.tsx
> +    const deleteCallback = (id: number) => {
add void for returns

2023-03-02 18:17 UTC, merged